apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstrs
  template:
    metadata:
      labels:
        app: myfirstrs
    spec:
      containers:
      - name: nginx
        image: nginx
